server:
  port: 8086
spring:
  application:
    name: User
  boot:
    admin:
      client:
        url: http://admin-server:3333
  zipkin:
    base-url: http://zipkin:9411
    enabled: true
  config:
    import: optional:configserver:http://config-server:8888


management:
  tracing:
    enabled: true
    sampling:
      probability: 1.0  # Trace 100% of requests (you can lower this in production)
  zipkin:
    tracing:
      endpoint: http://zipkin:9411/api/v2/spans
  endpoints:
    web:
      exposure:
        include: "*"

  endpoint:
    health:
      show-details: always

  metrics:
    export:
      prometheus:
        enabled: true


logging:
  level:
    root: INFO
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"
eureka:
  client:
    service-url:
      defaultZone: http://service-registry:8761/eureka
