spring:
  application:
    name: Service-Registry

  boot:
    admin:
      client:
        url: http://localhost:3333

server:
  port: 8761

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
