server:
  port: 8080

spring:
  application:
    name: API-Gateway
  boot:
    admin:
      client:
        url: http://admin-server:3333

  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: true
              lower-case-service-id: true
          routes:
            - id: microservice1
              uri: lb://microservice1
              predicates:
                - Path=/m1/**
            - id: microservice2
              uri: lb://microservice2
              predicates:
                - Path=/micro2/**
            - id: order-service
              uri: lb://order-service
              predicates:
                - Path=/orders/**
            - id: notification-service
              uri: lb://notification-service
              predicates:
                - Path=/notifications/**


#        - id: product-service
#          uri: lb://product-service
#          predicates:
#            - Path=/products/**

eureka:
  client:
    enabled: true
    service-url:
      defaultZone: http://service-registry:8761/eureka/
management:
  tracing:
    enabled: true
    sampling:
      probability: 1.0  # Trace 100% of requests (you can lower this in production)
  zipkin:
    tracing:
      endpoint: http://zipkin:9411/api/v2/spans
  prometheus:
    metrics:
      export:
        enabled: true
  endpoints:
    web:
      exposure:
        include: health, info, prometheus
