server:
  port: 8888

spring:
  application:
    name: Config-Server
  boot:
    admin:
      client:
        url: http://admin-server:3333
  profiles:
    active: native

  cloud:
    config:
      server:
        native:
          search-locations: file:/home/saasvaap/Desktop/Microservice project/MicroserviceTest/Configuration-Properties

management:
  endpoints:
    web:
      exposure:
        include: '*'
