
server:
  port: 8888

spring:
  application:
    name: Config-Server
  boot:
    admin:
      client:
        url: http://admin-server:3333
   # use file-based config

  cloud:
    config:
      server:
        native:
          search-locations: file:///C:\Users\LENOVO\OneDrive\Desktop\Zero\Shopsphere\Configuration-Properties

management:
  endpoints:
    web:
      exposure:
        include: '*'
