server:
  port: 8085

spring:
  application:
    name: microservice1
  boot:
    admin:
      client:
        url: http://localhost:3333

  zipkin:
    base-url: http://localhost:9411
    enabled: true

management:
  tracing:
    sampling:
      probability: 1.0  # Trace 100% of requests (you can lower this in production)

  endpoints:
    web:
      exposure:
        include: "*"

  endpoint:
    health:
      show-details: always

  metrics:
    export:
      prometheus:
        enabled: true
logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
