server:
  port: 8082

spring:
  application:
    name: user-service
  boot:
    admin:
      client:
        url: http://localhost:3333

  datasource:
    url: jdbc:mysql://localhost:3306/userdb?createDatabaseIfNotExist=true&useSSL=false
    username: root
    password: MyNewPassword!
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true

  zipkin:
    base-url: http://localhost:9411
    enabled: true

management:
  tracing:
    sampling:
      probability: 1.0  # Trace 100% of requests (you can lower this in production)

  endpoints:
    web:
      exposure:
        include: "*"

  endpoint:
    health:
      show-details: always

  metrics:
    export:
      prometheus:
        enabled: true

logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

info:
  app:
    name: User Service
    description: Microservice for managing users
    version: 1.0.0
